# Allow writing conductor and agent files in plan mode
[[rule]]
toolName = ["write_file", "replace"]
priority = 100 # prioritize over other extension policies
decision = "ask_user"
modes = ["plan"]
argsPattern = '"(?:file_path|path)":"(?:conductor/|\.agents/|~/\.agents/)[^"]*"'

# Allow tools used by conductor to set up project and install skills
[[rule]]
toolName = "run_shell_command"
commandPrefix = ["git status", "git diff", "ls", "mkdir", "cp", "git init", "git add", "git commit", "curl", "wget", "git", "python", "python3"]
decision = "ask_user"
priority = 100 # prioritize over other extension policies
modes = ["plan"]
